spring.application.name=Placement

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/placementDB
spring.datasource.username=postgres
spring.datasource.password=797555
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080